### ISSUE TITLE
Load log file error

### ISSUE THREAD

**Issue by 1Jesper1** [nextcloud/logreader#218] opened 2019-07-17 21:03 UTC
Error at "load log file" at logging page when trying to import empty txt file: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.

Maybe check on filetype?

**Comment by kesselb** [comment] 2019-07-17 21:22
Thank you :+1: 

Mind to use the [issue template](https://github.com/nextcloud/logreader/blob/master/.github/issue_template.md)? 

Cannot reproduce this issue with Nextcloud 16. I see "Invalid log file" with an empty txt file.

![image](https://user-images.githubusercontent.com/3902676/61412630-a0322d00-a8e9-11e9-88e6-9f4dfa1d36b5.png)

**Comment by 1Jesper1** [comment] 2019-07-17 21:32
@kesselb Sorry, you are totally right..
I was uploading an **PNG** file.

Browser:
Chrome

Version:
Nextcloud 16.0.3

**Comment by susnux** [comment] 2023-11-11 20:56
Fixed with https://github.com/nextcloud/logreader/pull/936

**Closed by susnux** 2023-11-11 20:56 UTC
Labels: bug, 1. to develop
