### ISSUE TITLE
Log reader froze after update from NC28 to NC 29.0.1

### ISSUE THREAD

**Issue by Sirdeckyor** [nextcloud/logreader#1264] opened 2024-05-29 09:26 UTC
### Steps to reproduce
1. in admin mode open log reader
2. scroll within logs
3. screen freeze and block backend

### Expected behaviour
Tell us what should happen
It is possible to scroll within log messages and select it to see details and copy log informations. 

### Actual behaviour
Tell us what happens instead

The screen freeze while scrolling within log messages, impossible to select one and open contextual menu to copy info.
The web interface bug and all menu are blocked. Only crashes of the page and relaunching reenable menus.

### Server configuration

**Operating system**:
Linux 5.15.0-107-generic x86_64
CPU: AMD Ryzen 5 3600 6-Core Processor (12 cores)
Memory: 15.51 GB

**Web server:**
NGINX

**Database:**
MariaDB 10.6.16

**PHP version:**
8.2.19
**Nextcloud version:** (see Nextcloud admin page)
29.0.1.1
**Where did you install Nextcloud from:**
Official web update 

**List of activated apps:**
Enabled:
  - activity: 2.21.1
  - announcementcenter: 6.8.1
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.4
  - camerarawpreviews: 0.8.5
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - cloud_py_api: 0.1.9
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - cospend: 1.6.1
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.4
  - groupfolders: 17.0.0
  - integration_openai: 2.0.1
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.6.1
  - maps: 1.4.0
  - mediadc: 0.3.8
  - memories: 7.3.1
  - music: 1.11.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - passwords: 2024.5.20
  - photos: 2.5.0
  - previewgenerator: 5.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recognize: 7.0.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.2
  - richdocumentscode: 24.4.201
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.1
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.djual.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.djual.eu",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "app_install_overwrite": [
            "bruteforcesettings",
            "groupfolders",
            "spreed",
            "richdocumentscode"
        ],
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "loglevel": 3,
        "logtimezone": "Europe\/Paris",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "default_phone_region": "FR",
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": "true",
        "trashbin_retention_obligation": "auto, 60",
        "maintenance_window_start": 1,
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie"
        ],
        "memories.db.triggers.fcu": true,
        "memories.gis_type": 1
    }
}

### Client configuration
**Browser:**
tested on Mozilla and Safari

**Operating system:**
MacOS 14.5

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by joshtrichards** [comment] 2024-05-30 22:07
Duplicate of #1262

**Closed by joshtrichards** 2024-05-30 22:07 UTC
