### ISSUE TITLE
Logging (Log Reader 2.0.0) not working in Nextcloud 11.0.3

### ISSUE THREAD

**Issue by Dave-REBL** [nextcloud/logreader#51] opened 2017-04-26 03:24 UTC
### Steps to reproduce
1. Upgrade from Nextcloud 11.0.2 to 11.0.3
2. Select Logging from the Admin menu

### Expected behaviour
Nextcloud logged events should be displayed

### Actual behaviour
'Loading circle' animation is displayed

### Server configuration
**Operating system**: Linux 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.29

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11.0.2

**Where did you install Nextcloud from:** Updater

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```

Enabled:
 - activity: 2.4.1
 - admin_audit: 1.1.0
 - comments: 1.1.0
 - dav: 1.1.1
 - federatedfilesharing: 1.1.1
 - files: 1.6.1
 - files_accesscontrol: 1.1.2
 - files_automatedtagging: 1.1.1
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - onlyoffice: 1.0.2
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - encryption
 - external
 - federation
 - files_retention
 - files_videoplayer
 - firstrunwizard
 - templateeditor
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocqznqxlb9f2",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.178"
    ],
    "allow_user_to_change_display_name": true,
    "datadirectory": "\/var\/www\/data",
    "overwrite.cli.url": "http:\/\/192.168.1.178",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "enable_avatars": true,
    "enable_previews": true,
    "loglevel": 1,
    "logdateformat": "Y-m-d H:i:s",
    "installed": true,
    "knowledgebaseenabled": false,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "remember_login_cookie_lifetime": 86400,
    "session_keepalive": false,
    "session_lifetime": 3600,
    "skeletondirectory": "",
    "maintenance": false,
    "theme": "",
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no.

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063

**Operating system:** Windows 10 Pro

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	{"reqId":"0X3uLfCCATyzsuvViJbR","remoteAddr":"23.16.129.165","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function format() on boolean\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/logreader\\\/lib\\\/Controller\\\/LogController.php(133): OCA\\\\LogReader\\\\Log\\\\LogIterator->current()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/logreader\\\/lib\\\/Controller\\\/LogController.php(73): OCA\\\\LogReader\\\\Controller\\\\LogController->responseFromIterator(Object(OCA\\\\LogReader\\\\Log\\\\LogIterator), 50, 0)\\n#2 [internal function]: OCA\\\\LogReader\\\\Controller\\\\LogController->get(50, 0)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\LogReader\\\\Controller\\\\LogController), 'get')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\LogReader\\\\Controller\\\\LogController), 'get')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\LogReader\\\\\\\\C...', 'get', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/logreader...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/logreader\\\/lib\\\/Log\\\/LogIterator.php\",\"Line\":75}","level":3,"time":"2017-04-26 02:38:47","method":"GET","url":"\/index.php\/apps\/logreader\/get?offset=0&count=50","user":"user","version":"11.0.3.2"}
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by qswroot** [comment] 2017-04-26 05:38
I can confirm I have the same problem; I recently upgraded from NC 10.0.5 to NC 11.0.3 and I also get the "Loading Circle" displayed. Everytime I try an entry is added to the global logfile:

{"reqId":"1GKTSTOZh8Pqj8hws8Cf","remoteAddr":"","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function format() on boolean\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/nextcloud1103\\/apps\\/logreader\\/lib\\/Controller\\/LogController.php(133): OCA\\LogReader\\Log\\LogIterator->current()\n#1 \\/var\\/www\\/nextcloud1103\\/apps\\/logreader\\/lib\\/Controller\\/LogController.php(73): OCA\\LogReader\\Controller\\LogController->responseFromIterator(Object(OCA\\LogReader\\Log\\LogIterator), 50, 0)\n#2 [internal function]: OCA\\LogReader\\Controller\\LogController->get(50, 0)\n#3 \\/var\\/www\\/nextcloud1103\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#4 \\/var\\/www\\/nextcloud1103\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\LogReader\\Controller\\LogController), 'get')\n#5 \\/var\\/www\\/nextcloud1103\\/lib\\/private\\/AppFramework\\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\LogReader\\Controller\\LogController), 'get')\n#6 \\/var\\/www\\/nextcloud1103\\/lib\\/private\\/AppFramework\\/Routing\\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\LogReader\\\\C...', 'get', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#7 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->_invoke(Array)\n#8 \\/var\\/www\\/nextcloud1103\\/lib\\/private\\/Route\\/Router.php(299): calluser_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#9 \\/var\\/www\\/nextcloud1103\\/lib\\/base.php(1010): OC\\Route\\Router->match('\\/apps\\/logreader...')\n#10 \\/var\\/www\\/nextcloud1103\\/index.php(40): OC::handleRequest()\n#11 {main}\",\"File\":\"\\/var\\/www\\/nextcloud1103\\/apps\\/logreader\\/lib\\/Log\\/LogIterator.php\",\"Line\":75}","level":3,"time":"April 25, 2017 15:07:56","method":"GET","url":"\/index.php\/apps\/logreader\/get?offset=0&count=50","user":"admin","version":"11.0.3.2"}

The page gets stuck and does not show anything.

Apache version: 2.4.18
OS: Ubuntu 16.04

**Comment by tessus** [comment] 2017-04-26 18:13
same as #50

**Comment by schleyk** [comment] 2017-05-14 18:38
Same Issue with the https://hub.docker.com/r/wonderfall/nextcloud/ Docker Image

**Comment by icewind1991** [comment] 2017-05-15 14:12
Duplicate of https://github.com/nextcloud/logreader/issues/51

**Closed by icewind1991** 2017-05-15 14:12 UTC
